### PR TITLE
feat: more block patterns (real estate, classified ads)

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Implements block patterns for real estate listings and classified ads (h/t @thomasguillot for the design).

**Note:** the patterns retain the hard-coded images from newspack-listings-demo.newspackstaging.com—should we replace those with placeholder images?

Addresses #38 but doesn't totally close it (could use other patterns in the future for: job listings, obituaries, events).

### How to test the changes in this Pull Request:

1. Add a new Marketplace Listing.
2. Go to the Block Inserter > Patterns > Newspack Listings.
3. Test the various block patterns in both the editor and on the front-end (3x Real Estate, 2x Classified)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by thomasguillot** [comment]
> Note: the patterns retain the hard-coded images from newspack-listings-demo.newspackstaging.com—should we replace those with placeholder images?

Could we do something similar to the Starter Content and import some random images?

**Comment by dkoo** [comment]
Hmm, that's an interesting idea. Since these are patterns and not actual posts being created, we'd probably need to construct the pattern strings on plugin activation and fetch the placeholder images then. Let me look into this. Thanks for the suggestion!

**Comment by dkoo** [comment]
> Could we do something similar to the Starter Content and import some random images?

Actually, in our other patterns, we've included slideshow blocks and image blocks, but empty. This seems kind of more user-friendly to me anyway since editors wouldn't have to remove placeholder images, they could just start adding their own right away. Would you be okay with following that tradition?

**Comment by thomasguillot** [comment]
> Actually, in our other patterns, we've included slideshow blocks and image blocks, but empty. This seems kind of more user-friendly to me anyway since editors wouldn't have to remove placeholder images, they could just start adding their own right away. Would you be okay with following that tradition?

Yes, ok. What would happen to the preview? Can we still have some generic images for the preview?

**Comment by dkoo** [comment]
> Yes, ok. What would happen to the preview? Can we still have some generic images for the preview?

Unfortunately the preview renders the pattern markup exactly, so we can't populate the previews with images while leaving the patterns empty. :(

**Comment by dkoo** [comment]
@thomasguillot I removed the placeholder images from the patterns in 1346e1b. Thanks!

**Comment by dkoo** [comment]
Oh, also wanted to point out that I incorporated the custom CSS you implemented on the demo site into the plugin. Since the styles overwrite core styles (instead of theme styles), I supposed it made sense to include them here.

**Review by adekbadek — CHANGES_REQUESTED** [review]
After inserting a pattern containing a Price block in a new Marketplace listing, the editor does not recognise the block (on WP `5.8-RC3`):

image

This block is also not insertable, but it renders fine on the front-end after publishing the listing.

**Comment by dkoo** [comment]
Huh, these must be new bugs related to WP 5.8. I'll investigate separately from this branch...

**Review by adekbadek — APPROVED** [review]

**Comment by dkoo** [comment]
@thomasguillot Does this look okay to you with the empty image/gallery blocks?

**Comment by thomasguillot** [comment]
> @thomasguillot Does this look okay to you with the empty image/gallery blocks?

No, Not really. Without any images in the preview, I don't really know what I'm inserting...

Screenshot 2021-07-16 at 11 11 24

**Comment by dkoo** [comment]
Hmm, maybe we can compromise by using a static Newspack branded asset instead of trying to pull in dynamic placeholder images. The dynamic part is what's complicated. I'll follow up on this after the 5.8 work is done.

**Comment by thomasguillot** [comment]
> Hmm, maybe we can compromise by using a static Newspack branded asset instead of trying to pull in dynamic placeholder images. The dynamic part is what's complicated. I'll follow up on this after the 5.8 work is done.

Sounds good, thank you @dkoo

**Comment by dkoo** [comment]
@thomasguillot I'd like to merge what we have now and come back to including the placeholder images in a future PR ([issue here](https://github.com/Automattic/newspack-listings/issues/98)). I think the usefulness of the new patterns outweighs the usability issue of the empty gallery blocks so I'd like to get this into publishers' hands earlier rather than later. Okay with you?

**Pull request merged**
