### PR TITLE
feat: use post categories and tags for all listing post types

### LINKED ISSUE #32: Use post categories and tags instead of custom taxonomies
Consider deprecating the custom taxonomies and allowing listings to use regular post categories and tags.

This would create another relationship between regular posts and listings and make it easier to do things like place certain ad units with specific categories and have them show up with both articles and listings.

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Deprecates the custom category and tag taxonomies that apply only to listing CPTs, in favor of regular post categories and tags. This will make it much easier to create relationships between listing and other types of site content.

Note: the `epic/phase-2` branch is currently a direct clone of `master`. I'll open all Phase 2 PRs against that branch so we can work on multiple features in parallel, then merge the epic branch into master when Phase 2 is release-ready.

Closes #32.

### How to test the changes in this Pull Request:

1. In WP admin, confirm that the **Listings > Categories** and **Listings > Tags** menu items now redirect to the post categories and tags.
2. Edit a listing of any type. Confirm that when searching for categories and tags, the suggestions are existing post categories and tags. Apply some categories and tags to several listing posts.
3. Create a query-mode curated list block in any page or post. Add some categories and tags to your query terms. Set the display options to show categories and tags. Confirm that it populates the listing posts you expect, with the matching terms, in both the editor and on the front-end.
4. Create another curated list block in "specific listings" mode. Set the display options to show categories and tags. Add several listings of various types and confirm that you see the correct categories and tags in both the editor and on the front-end.
5. View the front-end of an individual listing with categories and tags. Confirm that the categories shown on the singular page display correctly and link to the post archive pages for those categories (for now—in the future, these will need to link to archive pages for the listings, instead).
6. Confirm that on post category and tag archives, no listings appear. In the future, we will establish listings-specific archives to show the listings posts.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — CHANGES_REQUESTED** [review]
1. [This line](https://github.com/Automattic/newspack-listings/blob/922085584c1e61f46b77666fee6f62b5b32feb35/includes/class-newspack-listings-core.php#L70) should probably be removed, too.
2. Are we worried about migration? After this change, the existing CPT-specific categories & tags will be lost.

**Comment by dkoo** [comment]
> 1. [This line](https://github.com/Automattic/newspack-listings/blob/922085584c1e61f46b77666fee6f62b5b32feb35/includes/class-newspack-listings-core.php#L70) should probably be removed, too.

Removed in aadce2c.

> 2. Are we worried about migration? After this change, the existing CPT-specific categories & tags will be lost.

That's a great question. I don't believe any publishers are using Listings widely in production yet. What would you recommend as a migration strategy? Should we check for the assignment of term IDs from the custom taxonomies, and if they exist:

1. Check for a corresponding post category or tag term with the same name, and if it exists, assign that
2. If a corresponding post category or tag term doesn't exist with the same name, create and assign it?

**Comment by adekbadek** [comment]
>  I don't believe any publishers are using Listings widely in production yet. What would you recommend as a migration strategy?

We should check that assumption - if it's true, then that's a breaking change and that's that. If not, then on top of that I'd opt for a migration script, since that seems like a mostly DB-wrangling issue.

**Comment by dkoo** [comment]
> We should check that assumption - if it's true, then that's a breaking change and that's that. If not, then on top of that I'd opt for a migration script, since that seems like a mostly DB-wrangling issue.

Thanks for the feedback—I'll make a note for next week's publisher call to ask about Listings and category/tag usage

**Comment by dkoo** [comment]
In the meantime, let's proceed with this and we can maybe handle the migration separately if needed.

**Review by adekbadek — APPROVED** [review]
Note: to make this bump the major version, a [`BREAKING CHANGE` footer should be added in a commit message](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-footer).

**Pull request merged**
